# Generated by Django 2.1.5 on 2020-11-13 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_documento', models.CharField(max_length=20)),
                ('documento', models.CharField(max_length=11)),
                ('telefono', models.CharField(max_length=9)),
                ('funcion', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=10, max_digits=19)),
                ('foto', models.ImageField(blank=True, upload_to='asesor/')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='asesor',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Region'),
        ),
    ]
