# Generated by Django 2.1.5 on 2020-11-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asesor',
            name='correo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
