# Generated by Django 2.1.5 on 2020-11-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_asesor_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asesor',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
    ]
