# Generated by Django 2.1.5 on 2020-11-19 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='asunto',
        ),
    ]
